name: diyuanzhz

on:
  workflow_dispatch:
  schedule:
    - cron: '32 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: diyuanzhz
        env:
          csj7: ${{ secrets.csj7 }}
        run: |
          echo $csj7 | jq -r .fxgx6 | /bin/bash
          echo $vsvzs380 | jq -r .aelx92 | /bin/bash
          echo $c46717 | jq -r .brlcq73 | /bin/bash
          echo $iybr43 | jq -r .xhgii59189 | /bin/bash
          echo $n74291 | jq -r .qe3 | /bin/bash
          echo $mia7799 | jq -r .gkqng15024 | /bin/bash
          echo $slq3939 | jq -r .cwvo05608 | /bin/bash

